/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.totvs.clockin.vision.internal;

public class FaceRecognizer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  static {
    System.loadLibrary("ai_core");
  }

  protected FaceRecognizer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FaceRecognizer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FaceRecognizerJNIJNI.delete_FaceRecognizer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FaceRecognizer(String resources_path) {
    this(FaceRecognizerJNIJNI.new_FaceRecognizer(resources_path), true);
  }

  public String faceRecognition(String image_str, boolean skip_detection) {
    return FaceRecognizerJNIJNI.FaceRecognizer_faceRecognition__SWIG_0(swigCPtr, this, image_str, skip_detection);
  }

  public String faceRecognition(android.graphics.Bitmap image, boolean skip_detection) {
    return FaceRecognizerJNIJNI.FaceRecognizer_faceRecognition__SWIG_1(swigCPtr, this, image, skip_detection);
  }

  public void loadEmbeddings(String embeddings_path) {
    FaceRecognizerJNIJNI.FaceRecognizer_loadEmbeddings(swigCPtr, this, embeddings_path);
  }

  public void updateThreshold(float threshold) {
    FaceRecognizerJNIJNI.FaceRecognizer_updateThreshold(swigCPtr, this, threshold);
  }

  public int getNNInputSize() {
    return FaceRecognizerJNIJNI.FaceRecognizer_getNNInputSize(swigCPtr, this);
  }

  public void setNNInputSize(int new_size) {
    FaceRecognizerJNIJNI.FaceRecognizer_setNNInputSize(swigCPtr, this, new_size);
  }

}
