/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.totvs.clockin.vision.internal;

public class FaceRecognizerJNIJNI {
  public final static native long new_FaceRecognizer(String jarg1);
  public final static native String FaceRecognizer_faceRecognition__SWIG_0(long jarg1, FaceRecognizer jarg1_, String jarg2, boolean jarg3);
  public final static native String FaceRecognizer_faceRecognition__SWIG_1(long jarg1, FaceRecognizer jarg1_, Object jarg2, boolean jarg3);
  public final static native void FaceRecognizer_loadEmbeddings(long jarg1, FaceRecognizer jarg1_, String jarg2);
  public final static native void FaceRecognizer_updateThreshold(long jarg1, FaceRecognizer jarg1_, float jarg2);
  public final static native int FaceRecognizer_getNNInputSize(long jarg1, FaceRecognizer jarg1_);
  public final static native void FaceRecognizer_setNNInputSize(long jarg1, FaceRecognizer jarg1_, int jarg2);
  public final static native void delete_FaceRecognizer(long jarg1);
}